### ISSUE TITLE
Enhancement ADD deaths and recovered

### ISSUE THREAD

**Issue by conradKE** [Opensource-254/corona-api#1]
**Add this Confirmed deaths**

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

**Recovered**
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

**Comment by StanleyMasinde** [comment]
Any success @james-muriithi ?

**Comment by james-muriithi** [comment]
Yeah i solved it

**Comment by StanleyMasinde** [comment]
Nice one

**Comment by james-muriithi** [comment]
https://rona-api.herokuapp.com - for the combined data 
https://rona-api.herokuapp.com/reported - for reported cases 
https://rona-api.herokuapp.com/recovered - for recovered cases
 https://rona-api.herokuapp.com/deaths -for deaths

**Comment by StanleyMasinde** [comment]
> https://rona-api.herokuapp.com - for the combined data
> https://rona-api.herokuapp.com/reported - for reported cases
> https://rona-api.herokuapp.com/recovered - for recovered cases
> https://rona-api.herokuapp.com/deaths -for deaths

@azim254 hii iko sawa?
