### ISSUE TITLE
Add CORs errors

### ISSUE THREAD

**Issue by StanleyMasinde** [Opensource-254/corona-api#3]
**Is your feature request related to a problem? Please describe.**
Yes it is related to a problem all modern browsers will block requests to this API

**Describe the solution you'd like**
Add CORs headers allowing all origins `allow-origin: *`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by james-muriithi** [comment]
On it

**Comment by james-muriithi** [comment]
done
